/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class Library_Managment_SystemFrame extends javax.swing.JFrame {

    /**
     * Creates new form Admission_System
     */
    public Library_Managment_SystemFrame() {
        initComponents();
         java.awt.Toolkit kit=this.getToolkit();
        java.awt.Dimension d=kit.getScreenSize();
        this.setBounds(0,0,d.width,d.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        departmentButton = new javax.swing.JButton();
        programButton = new javax.swing.JButton();
        batchButton = new javax.swing.JButton();
        bookButton = new javax.swing.JButton();
        studentButton1 = new javax.swing.JButton();
        bookButton1 = new javax.swing.JButton();
        bookButton2 = new javax.swing.JButton();
        facultyButton1 = new javax.swing.JButton();
        facultyButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("UniversityOf Sindh");
        setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 51));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 690, 250, 90));

        departmentButton.setBackground(new java.awt.Color(0, 0, 0));
        departmentButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        departmentButton.setForeground(new java.awt.Color(255, 255, 0));
        departmentButton.setText("DEPARTMENT");
        departmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 250, 60));

        programButton.setBackground(new java.awt.Color(0, 0, 0));
        programButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        programButton.setForeground(new java.awt.Color(255, 255, 0));
        programButton.setText("PROGRAM");
        programButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programButtonActionPerformed(evt);
            }
        });
        getContentPane().add(programButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 250, 60));

        batchButton.setBackground(new java.awt.Color(0, 0, 0));
        batchButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        batchButton.setForeground(new java.awt.Color(255, 255, 0));
        batchButton.setText("BATCH");
        batchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 250, 60));

        bookButton.setBackground(new java.awt.Color(0, 0, 0));
        bookButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bookButton.setForeground(new java.awt.Color(255, 255, 0));
        bookButton.setText("BOOK DEFAULTER");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 250, 60));

        studentButton1.setBackground(new java.awt.Color(0, 0, 0));
        studentButton1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        studentButton1.setForeground(new java.awt.Color(255, 255, 51));
        studentButton1.setText("STUDENT");
        studentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(studentButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 250, 60));

        bookButton1.setBackground(new java.awt.Color(0, 0, 0));
        bookButton1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bookButton1.setForeground(new java.awt.Color(255, 255, 0));
        bookButton1.setText("BOOKS");
        bookButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(bookButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 250, 60));

        bookButton2.setBackground(new java.awt.Color(0, 0, 0));
        bookButton2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bookButton2.setForeground(new java.awt.Color(255, 255, 0));
        bookButton2.setText("BOOK ISSUE");
        bookButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(bookButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 250, 60));

        facultyButton1.setBackground(new java.awt.Color(255, 0, 255));
        facultyButton1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        facultyButton1.setText("L  I  B  R  A  R  Y __&__ M  A  N  A  G  M  E  N  T__&__ S  Y  S  T  E  M  ");
        facultyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(facultyButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 100));

        facultyButton2.setBackground(new java.awt.Color(0, 0, 0));
        facultyButton2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        facultyButton2.setForeground(new java.awt.Color(255, 255, 0));
        facultyButton2.setText("FACULTY");
        facultyButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(facultyButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 250, 60));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Bell_Labs_Program\\DataBase\\Library-Management.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentButtonActionPerformed
        // TODO add your handling code here:
        DepartmentFrame ob=new DepartmentFrame();
        ob.show();
    }//GEN-LAST:event_departmentButtonActionPerformed

    private void programButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programButtonActionPerformed
        // TODO add your handling code here:
           ProgramFrame ob=new ProgramFrame();
           ob.show();
    }//GEN-LAST:event_programButtonActionPerformed

    private void batchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchButtonActionPerformed
        // TODO add your handling code here:
         BatchFrame ob=new BatchFrame();
            ob.show();
    }//GEN-LAST:event_batchButtonActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
       BookDefaultersFrame ob;
        try {
           ob = new BookDefaultersFrame();
           ob.show();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Library_Managment_SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Library_Managment_SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }//GEN-LAST:event_bookButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void studentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButton1ActionPerformed
        // TODO add your handling code here:
        StudentFrame ob=new StudentFrame();
        ob.show();
    }//GEN-LAST:event_studentButton1ActionPerformed

    private void bookButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButton1ActionPerformed
        // TODO add your handling code here:
        
        BookFrame ob=new BookFrame();
        ob.show();
    }//GEN-LAST:event_bookButton1ActionPerformed

    private void bookButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButton2ActionPerformed
        // TODO add your handling code here:
        BookIssueFrame ob=new BookIssueFrame();
        ob.show();
    }//GEN-LAST:event_bookButton2ActionPerformed

    private void facultyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyButton1ActionPerformed

    private void facultyButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyButton2ActionPerformed
        try {
            // TODO add your handling code here:
            FacultyFrame ob=new FacultyFrame();
          ob.show();
        } catch (Exception ex) {
            Logger.getLogger(Library_Managment_SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_facultyButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library_Managment_SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library_Managment_SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library_Managment_SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library_Managment_SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library_Managment_SystemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batchButton;
    private javax.swing.JButton bookButton;
    private javax.swing.JButton bookButton1;
    private javax.swing.JButton bookButton2;
    private javax.swing.JButton departmentButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton facultyButton1;
    private javax.swing.JButton facultyButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton programButton;
    private javax.swing.JButton studentButton1;
    // End of variables declaration//GEN-END:variables
}
